export const REALTIME_OPERATIONAL_TABLES = [
  "checklist_responses",
  "checklist_runs",
  "deliveries",
  "expenses",
  "guests",
  "import_jobs",
  "incidents",
  "integration_connections",
  "integration_events",
  "integration_sync_jobs",
  "inventory_counts",
  "inventory_transactions",
  "inventory_transfers",
  "maintenance_requests",
  "manager_log_entries",
  "preshift_acknowledgements",
  "preshifts",
  "purchase_orders",
  "reservations",
  "service_availability_events",
  "service_shifts",
  "shift_closeouts",
  "sop_acknowledgements",
  "sop_documents",
  "sop_versions",
  "time_breaks",
  "time_entries",
  "time_entry_corrections",
  "tasks",
  "waste_records",
] as const;

export type RealtimeOperationalTable =
  (typeof REALTIME_OPERATIONAL_TABLES)[number];
