export const REALTIME_OPERATIONAL_TABLES = [
  "checklist_responses",
  "checklist_runs",
  "closeout_attachments",
  "deliveries",
  "delivery_lines",
  "employee_job_roles",
  "expenses",
  "guests",
  "import_jobs",
  "incidents",
  "integration_connections",
  "integration_events",
  "integration_sync_jobs",
  "inventory_counts",
  "inventory_transactions",
  "inventory_transfers",
  "maintenance_requests",
  "manager_log_entries",
  "preshift_acknowledgements",
  "preshifts",
  "purchase_orders",
  "reservations",
  "schedule_templates",
  "schedule_template_shifts",
  "schedules",
  "service_availability_events",
  "service_shifts",
  "shift_acknowledgements",
  "shift_closeouts",
  "shift_swap_offers",
  "shift_swap_requests",
  "shifts",
  "sop_acknowledgements",
  "sop_documents",
  "sop_versions",
  "time_breaks",
  "time_entries",
  "time_entry_corrections",
  "tasks",
  "tip_adjustments",
  "tip_allocations",
  "tip_pool_eligibility_rules",
  "tip_pool_policies",
  "tip_pool_policy_versions",
  "tip_run_participants",
  "tip_runs",
  "tip_sources",
  "waste_records",
] as const;

export type RealtimeOperationalTable =
  (typeof REALTIME_OPERATIONAL_TABLES)[number];
