-- Le Yard OS: owner-authored tip-policy drafts and retention configuration.
-- No operational values are seeded. Every mutation is actor-bound, idempotent,
-- tenant-checked, and captured by the existing audit triggers.
-- FROZEN after the focused and full-chain PGlite verification. Follow-up
-- schema changes must use a new forward migration; do not edit this file.

create unique index if not exists tip_pool_policies_name_ci_unique
on public.tip_pool_policies (organization_id, lower(name));

create function public.configure_tip_pool_policy(
  p_request_id uuid,
  p_policy_id uuid,
  p_organization_id uuid,
  p_location_id uuid,
  p_name text,
  p_description text default null,
  p_is_active boolean default true
)
returns public.tip_pool_policies
language plpgsql security definer
set search_path = ''
set row_security = off
as $$
declare
  actor_id uuid := auth.uid();
  clean_name text := btrim(p_name);
  clean_description text := nullif(btrim(p_description), '');
  policy_row public.tip_pool_policies%rowtype;
begin
  if actor_id is null then
    raise exception 'Authentication is required' using errcode = '42501';
  end if;
  if not public.can_manage_org(p_organization_id) then
    raise exception 'Owner or Admin access is required to configure tip policies'
      using errcode = '42501';
  end if;
  if length(clean_name) not between 1 and 120
    or length(coalesce(clean_description, '')) > 2000 then
    raise exception 'Invalid tip policy name or description' using errcode = '22023';
  end if;
  if p_location_id is not null and not exists (
    select 1
    from public.locations location
    where location.organization_id = p_organization_id
      and location.id = p_location_id
      and location.is_active
  ) then
    raise exception 'Tip policy location is unavailable in this organization'
      using errcode = '23514';
  end if;

  select * into policy_row
  from public.tip_pool_policies policy
  where policy.id = p_policy_id
  for update;
  if policy_row.id is not null then
    if policy_row.organization_id is distinct from p_organization_id then
      raise exception 'Tip policy scope is invalid' using errcode = '42501';
    end if;
    if policy_row.location_id is distinct from p_location_id then
      raise exception 'A tip policy location scope is immutable; create a new policy'
        using errcode = '23514';
    end if;
  end if;

  if not private.claim_operation_request(
    p_request_id,
    'tip-policy.configure',
    p_organization_id,
    p_location_id,
    p_policy_id,
    jsonb_build_object(
      'name', clean_name,
      'description', clean_description,
      'is_active', p_is_active
    )
  ) then
    select * into policy_row
    from public.tip_pool_policies policy
    where policy.id = p_policy_id;
    if policy_row.id is null
      or policy_row.organization_id is distinct from p_organization_id
      or policy_row.location_id is distinct from p_location_id
      or policy_row.name is distinct from clean_name
      or policy_row.description is distinct from clean_description
      or policy_row.is_active is distinct from p_is_active then
      raise exception 'Tip policy replay no longer matches its result'
        using errcode = '23505';
    end if;
    return policy_row;
  end if;

  if policy_row.id is null then
    insert into public.tip_pool_policies (
      id, organization_id, location_id, name, description, is_active, created_by
    ) values (
      p_policy_id, p_organization_id, p_location_id, clean_name,
      clean_description, p_is_active, actor_id
    )
    returning * into policy_row;
  else
    update public.tip_pool_policies policy
    set name = clean_name,
        description = clean_description,
        is_active = p_is_active,
        updated_at = clock_timestamp()
    where policy.id = p_policy_id
    returning * into policy_row;
  end if;

  perform private.complete_operation_request(p_request_id);
  return policy_row;
end
$$;

create function public.save_tip_pool_policy_draft(
  p_request_id uuid,
  p_policy_id uuid,
  p_policy_version_id uuid,
  p_distribution_method public.tip_distribution_method,
  p_effective_from date,
  p_effective_to date,
  p_closeout_sources text[],
  p_eligibility_rules jsonb
)
returns public.tip_pool_policy_versions
language plpgsql security definer
set search_path = ''
set row_security = off
as $$
declare
  actor_id uuid := auth.uid();
  policy_row public.tip_pool_policies%rowtype;
  version_row public.tip_pool_policy_versions%rowtype;
  next_version integer;
  source_count integer;
  normalized_sources text[];
  normalized_rules jsonb;
  existing_rules jsonb;
  role_count integer;
begin
  if actor_id is null then
    raise exception 'Authentication is required' using errcode = '42501';
  end if;

  select * into policy_row
  from public.tip_pool_policies policy
  where policy.id = p_policy_id
  for update;
  if policy_row.id is null then
    raise exception 'Tip policy not found' using errcode = 'P0002';
  end if;
  if not public.can_manage_org(policy_row.organization_id) then
    raise exception 'Owner or Admin access is required to author tip policy drafts'
      using errcode = '42501';
  end if;
  if p_distribution_method not in ('hours', 'weighted_hours') then
    raise exception 'Tip distribution must use hours or weighted hours'
      using errcode = '22023';
  end if;
  if p_effective_from is null
    or (p_effective_to is not null and p_effective_to < p_effective_from) then
    raise exception 'Invalid tip policy effective dates' using errcode = '22023';
  end if;

  select count(*), array_agg(distinct source_name order by source_name)
  into source_count, normalized_sources
  from unnest(coalesce(p_closeout_sources, '{}'::text[])) source(source_name)
  where source_name in ('card_tips', 'cash_tips', 'service_charges');
  if source_count = 0
    or source_count <> cardinality(coalesce(p_closeout_sources, '{}'::text[]))
    or source_count <> cardinality(normalized_sources) then
    raise exception 'Choose one or more unique supported closeout sources'
      using errcode = '22023';
  end if;

  if jsonb_typeof(p_eligibility_rules) <> 'array'
    or jsonb_array_length(p_eligibility_rules) not between 1 and 200 then
    raise exception 'Tip eligibility rules must be a non-empty array'
      using errcode = '22023';
  end if;
  if exists (
    select 1
    from jsonb_array_elements(p_eligibility_rules) rule(value)
    where jsonb_typeof(rule.value) <> 'object'
      or not rule.value ?& array['job_role_id', 'eligible', 'points', 'minimum_minutes']
      or exists (
        select 1
        from jsonb_object_keys(rule.value) key(name)
        where key.name not in ('job_role_id', 'eligible', 'points', 'minimum_minutes')
      )
  ) then
    raise exception 'Tip eligibility rule objects contain invalid fields'
      using errcode = '22023';
  end if;
  if exists (
    select 1
    from jsonb_to_recordset(p_eligibility_rules) rule(
      job_role_id uuid,
      eligible boolean,
      points numeric,
      minimum_minutes integer
    )
    where rule.job_role_id is null
      or rule.eligible is null
      or rule.points is null
      or rule.minimum_minutes is null
      or rule.points < 0
      or rule.points > 1000
      or rule.minimum_minutes not between 0 and 1440
      or (p_distribution_method = 'hours' and rule.points <> 1)
      or (p_distribution_method = 'weighted_hours' and rule.eligible and rule.points <= 0)
  ) then
    raise exception 'Tip eligibility rule values are invalid'
      using errcode = '22023';
  end if;
  if not exists (
    select 1
    from jsonb_to_recordset(p_eligibility_rules) rule(
      job_role_id uuid,
      eligible boolean,
      points numeric,
      minimum_minutes integer
    )
    where rule.eligible
  ) then
    raise exception 'At least one job role must be eligible for the tip pool'
      using errcode = '23514';
  end if;
  if (
    select count(distinct rule.job_role_id)
    from jsonb_to_recordset(p_eligibility_rules) rule(
      job_role_id uuid,
      eligible boolean,
      points numeric,
      minimum_minutes integer
    )
  ) <> jsonb_array_length(p_eligibility_rules) then
    raise exception 'Each job role may appear only once in a tip policy version'
      using errcode = '23505';
  end if;
  select count(*) into role_count
  from public.job_roles role
  where role.organization_id = policy_row.organization_id
    and role.is_active
    and role.id in (
      select rule.job_role_id
      from jsonb_to_recordset(p_eligibility_rules) rule(
        job_role_id uuid,
        eligible boolean,
        points numeric,
        minimum_minutes integer
      )
    );
  if role_count <> jsonb_array_length(p_eligibility_rules) then
    raise exception 'Every tip eligibility rule must use an active job role in this organization'
      using errcode = '23514';
  end if;

  select jsonb_agg(
    jsonb_build_object(
      'job_role_id', rule.job_role_id,
      'eligible', rule.eligible,
      'points', rule.points,
      'minimum_minutes', rule.minimum_minutes
    ) order by rule.job_role_id
  ) into normalized_rules
  from jsonb_to_recordset(p_eligibility_rules) rule(
    job_role_id uuid,
    eligible boolean,
    points numeric,
    minimum_minutes integer
  );

  select * into version_row
  from public.tip_pool_policy_versions version
  where version.id = p_policy_version_id
  for update;
  if version_row.id is not null then
    if version_row.organization_id is distinct from policy_row.organization_id
      or version_row.policy_id is distinct from policy_row.id then
      raise exception 'Tip policy version scope is invalid' using errcode = '42501';
    end if;
  end if;

  if not private.claim_operation_request(
    p_request_id,
    'tip-policy-draft.save',
    policy_row.organization_id,
    policy_row.location_id,
    p_policy_version_id,
    jsonb_build_object(
      'policy_id', policy_row.id,
      'distribution_method', p_distribution_method,
      'effective_from', p_effective_from,
      'effective_to', p_effective_to,
      'closeout_sources', to_jsonb(normalized_sources),
      'eligibility_rules', normalized_rules
    )
  ) then
    select * into version_row
    from public.tip_pool_policy_versions version
    where version.id = p_policy_version_id;
    select coalesce(jsonb_agg(
      jsonb_build_object(
        'job_role_id', rule.job_role_id,
        'eligible', rule.eligible,
        'points', rule.points,
        'minimum_minutes', rule.minimum_minutes
      ) order by rule.job_role_id
    ), '[]'::jsonb) into existing_rules
    from public.tip_pool_eligibility_rules rule
    where rule.policy_version_id = p_policy_version_id;
    if version_row.id is null
      or version_row.policy_id is distinct from policy_row.id
      or version_row.distribution_method is distinct from p_distribution_method
      or version_row.effective_from is distinct from p_effective_from
      or version_row.effective_to is distinct from p_effective_to
      or version_row.source_rules is distinct from jsonb_build_object(
        'closeout_sources', to_jsonb(normalized_sources)
      )
      or existing_rules is distinct from normalized_rules then
      raise exception 'Tip policy draft replay no longer matches its result'
        using errcode = '23505';
    end if;
    return version_row;
  end if;

  if not policy_row.is_active then
    raise exception 'Reactivate the tip policy before authoring a draft'
      using errcode = '23514';
  end if;
  if version_row.id is not null and version_row.approved_at is not null then
    raise exception 'Approved tip policy versions are immutable' using errcode = '42501';
  end if;
  if version_row.id is not null and version_row.created_by is distinct from actor_id then
    raise exception 'Only the draft creator may edit this tip policy version'
      using errcode = '42501';
  end if;

  if version_row.id is null then
    select coalesce(max(version.version), 0) + 1 into next_version
    from public.tip_pool_policy_versions version
    where version.policy_id = policy_row.id;
    insert into public.tip_pool_policy_versions (
      id, organization_id, policy_id, version, distribution_method,
      effective_from, effective_to, source_rules, rounding_rule, created_by
    ) values (
      p_policy_version_id, policy_row.organization_id, policy_row.id, next_version,
      p_distribution_method, p_effective_from, p_effective_to,
      jsonb_build_object('closeout_sources', to_jsonb(normalized_sources)),
      'largest_remainder', actor_id
    )
    returning * into version_row;
  else
    update public.tip_pool_policy_versions version
    set distribution_method = p_distribution_method,
        effective_from = p_effective_from,
        effective_to = p_effective_to,
        source_rules = jsonb_build_object(
          'closeout_sources', to_jsonb(normalized_sources)
        ),
        rounding_rule = 'largest_remainder'
    where version.id = p_policy_version_id
    returning * into version_row;
    delete from public.tip_pool_eligibility_rules rule
    where rule.policy_version_id = p_policy_version_id;
  end if;

  insert into public.tip_pool_eligibility_rules (
    organization_id, policy_version_id, job_role_id,
    eligible, points, minimum_minutes
  )
  select
    policy_row.organization_id,
    version_row.id,
    rule.job_role_id,
    rule.eligible,
    rule.points,
    rule.minimum_minutes
  from jsonb_to_recordset(normalized_rules) rule(
    job_role_id uuid,
    eligible boolean,
    points numeric,
    minimum_minutes integer
  );

  perform private.complete_operation_request(p_request_id);
  return version_row;
end
$$;

create function public.configure_retention_policy(
  p_request_id uuid,
  p_policy_id uuid,
  p_organization_id uuid,
  p_data_class text,
  p_retention_days integer,
  p_legal_hold boolean,
  p_notes text default null
)
returns public.retention_policies
language plpgsql security definer
set search_path = ''
set row_security = off
as $$
declare
  actor_id uuid := auth.uid();
  clean_data_class text := lower(btrim(p_data_class));
  clean_notes text := nullif(btrim(p_notes), '');
  policy_row public.retention_policies%rowtype;
  target_id uuid;
begin
  if actor_id is null then
    raise exception 'Authentication is required' using errcode = '42501';
  end if;
  if not public.can_manage_org(p_organization_id) then
    raise exception 'Owner or Admin access is required to configure retention'
      using errcode = '42501';
  end if;
  if clean_data_class !~ '^[a-z][a-z0-9_]{1,79}$'
    or (p_retention_days is not null and p_retention_days not between 1 and 36500)
    or length(coalesce(clean_notes, '')) > 2000 then
    raise exception 'Invalid retention policy configuration' using errcode = '22023';
  end if;

  select * into policy_row
  from public.retention_policies policy
  where policy.organization_id = p_organization_id
    and policy.data_class = clean_data_class
  for update;
  target_id := coalesce(policy_row.id, p_policy_id);

  if not private.claim_operation_request(
    p_request_id,
    'retention-policy.configure',
    p_organization_id,
    null,
    target_id,
    jsonb_build_object(
      'data_class', clean_data_class,
      'retention_days', p_retention_days,
      'legal_hold', p_legal_hold,
      'notes', clean_notes
    )
  ) then
    select * into policy_row
    from public.retention_policies policy
    where policy.id = target_id;
    if policy_row.id is null
      or policy_row.organization_id is distinct from p_organization_id
      or policy_row.data_class is distinct from clean_data_class
      or policy_row.retention_days is distinct from p_retention_days
      or policy_row.legal_hold is distinct from p_legal_hold
      or policy_row.notes is distinct from clean_notes then
      raise exception 'Retention policy replay no longer matches its result'
        using errcode = '23505';
    end if;
    return policy_row;
  end if;

  if policy_row.id is null then
    insert into public.retention_policies (
      id, organization_id, data_class, retention_days, legal_hold,
      configured_by, configured_at, notes
    ) values (
      target_id, p_organization_id, clean_data_class, p_retention_days,
      p_legal_hold, actor_id, clock_timestamp(), clean_notes
    )
    returning * into policy_row;
  else
    update public.retention_policies policy
    set retention_days = p_retention_days,
        legal_hold = p_legal_hold,
        configured_by = actor_id,
        configured_at = clock_timestamp(),
        notes = clean_notes,
        updated_at = clock_timestamp()
    where policy.id = policy_row.id
    returning * into policy_row;
  end if;

  perform private.complete_operation_request(p_request_id);
  return policy_row;
end
$$;

-- Configuration rows are command-only for browser-authenticated actors.
-- Read policies remain intact; service-role maintenance remains available.
revoke insert, update, delete on public.tip_pool_policies from authenticated;
revoke insert, update, delete on public.tip_pool_policy_versions from authenticated;
revoke insert, update, delete on public.tip_pool_eligibility_rules from authenticated;
revoke insert, update, delete on public.retention_policies from authenticated;

revoke all on function public.configure_tip_pool_policy(
  uuid, uuid, uuid, uuid, text, text, boolean
) from public, anon;
revoke all on function public.save_tip_pool_policy_draft(
  uuid, uuid, uuid, public.tip_distribution_method, date, date, text[], jsonb
) from public, anon;
revoke all on function public.configure_retention_policy(
  uuid, uuid, uuid, text, integer, boolean, text
) from public, anon;

grant execute on function public.configure_tip_pool_policy(
  uuid, uuid, uuid, uuid, text, text, boolean
) to authenticated;
grant execute on function public.save_tip_pool_policy_draft(
  uuid, uuid, uuid, public.tip_distribution_method, date, date, text[], jsonb
) to authenticated;
grant execute on function public.configure_retention_policy(
  uuid, uuid, uuid, text, integer, boolean, text
) to authenticated;

comment on function public.configure_tip_pool_policy(
  uuid, uuid, uuid, uuid, text, text, boolean
) is 'Idempotently creates, edits, or deactivates an Owner/Admin-authored tip policy without inventing policy values.';
comment on function public.save_tip_pool_policy_draft(
  uuid, uuid, uuid, public.tip_distribution_method, date, date, text[], jsonb
) is 'Idempotently saves a complete hours-based tip policy draft and replaces its role rules atomically; approval remains a separate-person command.';
comment on function public.configure_retention_policy(
  uuid, uuid, uuid, text, integer, boolean, text
) is 'Idempotently records an Owner/Admin-approved retention decision; null days represent no automated deletion window.';
