-- Le Yard OS: Owner/Admin inventory catalog configuration.
-- Catalog identities are preserved, direct browser DML is removed, and every
-- command is actor-bound and exactly replayable through operation_requests.
-- FROZEN after the focused PGlite and UI/workflow verification. Follow-up
-- schema changes must use a new forward migration; do not edit this file.

alter table public.measurement_units
add column is_active boolean not null default true,
add column updated_at timestamptz not null default now();

alter table public.unit_conversions
add column is_active boolean not null default true,
add column updated_at timestamptz not null default now();

alter table public.inventory_categories
add column is_active boolean not null default true,
add column updated_at timestamptz not null default now();

alter table public.vendor_items
add column is_active boolean not null default true;

create unique index unit_conversions_identity_unique
on public.unit_conversions (organization_id, from_unit_id, to_unit_id, item_id)
nulls not distinct;

create trigger measurement_units_updated_at
before update on public.measurement_units
for each row execute function public.touch_updated_at();

create trigger unit_conversions_updated_at
before update on public.unit_conversions
for each row execute function public.touch_updated_at();

create trigger inventory_categories_updated_at
before update on public.inventory_categories
for each row execute function public.touch_updated_at();

create table public.inventory_recipe_versions (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  recipe_id uuid not null,
  version_number integer not null check (version_number > 0),
  snapshot jsonb not null check (jsonb_typeof(snapshot) = 'object'),
  changed_by uuid not null references auth.users(id) on delete restrict,
  created_at timestamptz not null default now(),
  foreign key (organization_id, recipe_id)
    references public.recipes(organization_id, id) on delete restrict,
  unique (recipe_id, version_number),
  unique (organization_id, id)
);

alter table public.inventory_recipe_versions enable row level security;
alter table public.inventory_recipe_versions force row level security;

create policy inventory_recipe_version_read
on public.inventory_recipe_versions for select to authenticated
using (public.can_read_management_org(organization_id));

create trigger inventory_recipe_versions_audit
after insert or update or delete on public.inventory_recipe_versions
for each row execute function public.capture_audit_event();

create or replace function private.inventory_conversion_multiplier(
  p_organization_id uuid,
  p_inventory_item_id uuid,
  p_from_unit_id uuid,
  p_to_unit_id uuid
)
returns numeric
language plpgsql stable security definer
set search_path = ''
set row_security = off
as $$
declare
  result numeric;
begin
  if p_from_unit_id = p_to_unit_id then return 1; end if;

  select case
    when conversion.from_unit_id = p_from_unit_id then conversion.multiplier
    else 1 / conversion.multiplier
  end
  into result
  from public.unit_conversions conversion
  where conversion.organization_id = p_organization_id
    and conversion.is_active
    and (conversion.item_id is null or conversion.item_id = p_inventory_item_id)
    and (
      (conversion.from_unit_id = p_from_unit_id and conversion.to_unit_id = p_to_unit_id)
      or
      (conversion.from_unit_id = p_to_unit_id and conversion.to_unit_id = p_from_unit_id)
    )
  order by (conversion.item_id = p_inventory_item_id) desc,
    (conversion.from_unit_id = p_from_unit_id) desc,
    conversion.id
  limit 1;

  if result is null then
    raise exception 'The selected unit has no active canonical conversion for this item'
      using errcode = '23514';
  end if;
  return result;
end
$$;

create function public.configure_inventory_catalog(
  p_request_id uuid,
  p_organization_id uuid,
  p_command text,
  p_payload jsonb
)
returns jsonb
language plpgsql security definer
set search_path = ''
set row_security = off
as $$
#variable_conflict use_variable
declare
  actor_id uuid := auth.uid();
  target_id uuid;
  claim_location_id uuid;
  claimed boolean;
  clean_command text := lower(btrim(coalesce(p_command, '')));
  canonical_payload jsonb;
  clean_name text;
  clean_symbol text;
  clean_dimension text;
  clean_sku text;
  clean_description text;
  clean_contact text;
  clean_email text;
  clean_phone text;
  clean_terms text;
  clean_account text;
  from_unit_id uuid;
  to_unit_id uuid;
  unit_id uuid;
  base_unit_id uuid;
  category_id uuid;
  parent_id uuid;
  item_id uuid;
  vendor_id uuid;
  location_id uuid;
  recipe_id uuid;
  multiplier_value numeric;
  quantity_value numeric;
  reorder_value numeric;
  price_cents bigint;
  effective_date date;
  existing_par_id uuid;
  effective_at timestamptz;
  active_value boolean;
  preferred_value boolean;
  track_value boolean;
  base_value boolean;
  version_number integer;
  ingredients jsonb;
  snapshot_ingredients jsonb;
  existing_unit public.measurement_units%rowtype;
  from_unit public.measurement_units%rowtype;
  to_unit public.measurement_units%rowtype;
  existing_conversion public.unit_conversions%rowtype;
  existing_category public.inventory_categories%rowtype;
  existing_vendor public.vendors%rowtype;
  existing_item public.inventory_items%rowtype;
  existing_vendor_item public.vendor_items%rowtype;
  existing_recipe public.recipes%rowtype;
begin
  if actor_id is null then
    raise exception 'Authentication is required' using errcode = '42501';
  end if;
  if p_request_id is null or p_organization_id is null
    or jsonb_typeof(p_payload) <> 'object'
    or clean_command not in (
      'unit.save', 'conversion.save', 'category.save', 'vendor.save',
      'item.save', 'vendor_item.save', 'par.set', 'recipe.save'
    ) then
    raise exception 'A valid inventory catalog command is required' using errcode = '22023';
  end if;
  if not public.can_manage_org(p_organization_id) then
    raise exception 'Owner or admin access is required to configure inventory'
      using errcode = '42501';
  end if;

  target_id := case
    when nullif(p_payload ->> 'id', '') is null then p_request_id
    else (p_payload ->> 'id')::uuid
  end;
  if clean_command = 'par.set' then
    location_id := (p_payload ->> 'locationId')::uuid;
    item_id := (p_payload ->> 'inventoryItemId')::uuid;
    effective_date := (p_payload ->> 'effectiveFrom')::date;
    if location_id is null or item_id is null or effective_date is null then
      raise exception 'A location, item, and effective date are required'
        using errcode = '22023';
    end if;
    perform pg_advisory_xact_lock(hashtextextended(
      'inventory-par:' || p_organization_id::text || ':' || location_id::text
        || ':' || item_id::text || ':' || effective_date::text,
      0
    ));
    select par.id into existing_par_id
    from public.inventory_par_levels par
    where par.organization_id = p_organization_id
      and par.location_id = location_id
      and par.inventory_item_id = item_id
      and par.effective_from = effective_date;
    target_id := coalesce(existing_par_id, p_request_id);
    claim_location_id := location_id;
  end if;
  canonical_payload := jsonb_build_object(
    'command', clean_command,
    'payload', p_payload
  );
  claimed := private.claim_operation_request(
    p_request_id,
    'inventory.catalog.' || clean_command,
    p_organization_id,
    claim_location_id,
    target_id,
    canonical_payload
  );
  if not claimed then
    return jsonb_build_object(
      'id', target_id,
      'command', clean_command,
      'replayed', true
    );
  end if;

  if clean_command = 'unit.save' then
    clean_name := nullif(btrim(p_payload ->> 'name'), '');
    clean_symbol := nullif(btrim(p_payload ->> 'symbol'), '');
    clean_dimension := lower(btrim(coalesce(p_payload ->> 'dimension', '')));
    base_value := coalesce((p_payload ->> 'isBase')::boolean, false);
    active_value := coalesce((p_payload ->> 'isActive')::boolean, true);
    if clean_name is null or length(clean_name) > 120
      or clean_symbol is null or length(clean_symbol) > 24
      or clean_dimension not in ('count', 'mass', 'volume', 'length') then
      raise exception 'A valid unit name, symbol, and dimension are required'
        using errcode = '22023';
    end if;
    select * into existing_unit from public.measurement_units unit
    where unit.id = target_id for update;
    if existing_unit.id is not null and existing_unit.organization_id <> p_organization_id then
      raise exception 'Measurement unit not found' using errcode = 'P0002';
    end if;
    if existing_unit.id is not null
      and (existing_unit.symbol <> clean_symbol or existing_unit.dimension <> clean_dimension)
      and exists (
        select 1 from public.inventory_items item where item.base_unit_id = target_id
        union all
        select 1 from public.vendor_items vendor_item where vendor_item.purchase_unit_id = target_id
        union all
        select 1 from public.recipe_ingredients ingredient where ingredient.unit_id = target_id
        union all
        select 1 from public.recipes recipe where recipe.yield_unit_id = target_id
      ) then
      raise exception 'A referenced unit cannot change symbol or dimension'
        using errcode = '23514';
    end if;
    if not active_value and exists (
      select 1 from public.inventory_items item
      where item.organization_id = p_organization_id and item.base_unit_id = target_id and item.is_active
      union all
      select 1 from public.vendor_items vendor_item
      where vendor_item.organization_id = p_organization_id and vendor_item.purchase_unit_id = target_id and vendor_item.is_active
      union all
      select 1 from public.unit_conversions conversion
      where conversion.organization_id = p_organization_id
        and (conversion.from_unit_id = target_id or conversion.to_unit_id = target_id)
        and conversion.is_active
      union all
      select 1 from public.recipes recipe
      where recipe.organization_id = p_organization_id and recipe.yield_unit_id = target_id and recipe.is_active
    ) then
      raise exception 'Deactivate dependent catalog records before this unit'
        using errcode = '23514';
    end if;
    if existing_unit.id is null then
      insert into public.measurement_units (
        id, organization_id, name, symbol, dimension, is_base, is_active
      ) values (
        target_id, p_organization_id, clean_name, clean_symbol,
        clean_dimension, base_value, active_value
      );
    else
      update public.measurement_units unit
      set name = clean_name,
          symbol = clean_symbol,
          dimension = clean_dimension,
          is_base = base_value,
          is_active = active_value
      where unit.id = target_id;
    end if;

  elsif clean_command = 'conversion.save' then
    from_unit_id := (p_payload ->> 'fromUnitId')::uuid;
    to_unit_id := (p_payload ->> 'toUnitId')::uuid;
    item_id := nullif(p_payload ->> 'inventoryItemId', '')::uuid;
    multiplier_value := (p_payload ->> 'multiplier')::numeric;
    active_value := coalesce((p_payload ->> 'isActive')::boolean, true);
    if from_unit_id is null or to_unit_id is null or multiplier_value is null
      or from_unit_id = to_unit_id or multiplier_value <= 0
      or multiplier_value >= 1000000000000 or scale(multiplier_value) > 8 then
      raise exception 'A positive conversion between different units is required'
        using errcode = '22023';
    end if;
    select * into from_unit from public.measurement_units unit
    where unit.id = from_unit_id and unit.organization_id = p_organization_id and unit.is_active;
    select * into to_unit from public.measurement_units unit
    where unit.id = to_unit_id and unit.organization_id = p_organization_id and unit.is_active;
    if from_unit.id is null or to_unit.id is null then
      raise exception 'Conversion units must be active tenant units' using errcode = '23514';
    end if;
    if item_id is null and from_unit.dimension <> to_unit.dimension then
      raise exception 'General conversions require matching dimensions' using errcode = '23514';
    end if;
    if item_id is not null then
      select * into existing_item from public.inventory_items item
      where item.id = item_id and item.organization_id = p_organization_id and item.is_active;
      if existing_item.id is null
        or (from_unit_id <> existing_item.base_unit_id and to_unit_id <> existing_item.base_unit_id) then
        raise exception 'Item conversions must connect directly to its canonical base unit'
          using errcode = '23514';
      end if;
    end if;
    if not active_value and exists (
      select 1
      from public.vendor_items vendor_item
      join public.inventory_items item
        on item.organization_id = vendor_item.organization_id
       and item.id = vendor_item.inventory_item_id
      where vendor_item.organization_id = p_organization_id
        and vendor_item.is_active and item.is_active
        and (item_id is null or item.id = item_id)
        and (
          (vendor_item.purchase_unit_id = from_unit_id and item.base_unit_id = to_unit_id)
          or (vendor_item.purchase_unit_id = to_unit_id and item.base_unit_id = from_unit_id)
        )
      union all
      select 1
      from public.recipe_ingredients ingredient
      join public.inventory_items item
        on item.organization_id = ingredient.organization_id
       and item.id = ingredient.inventory_item_id
      join public.recipes recipe
        on recipe.organization_id = ingredient.organization_id
       and recipe.id = ingredient.recipe_id
      where ingredient.organization_id = p_organization_id
        and recipe.is_active and item.is_active
        and (item_id is null or item.id = item_id)
        and (
          (ingredient.unit_id = from_unit_id and item.base_unit_id = to_unit_id)
          or (ingredient.unit_id = to_unit_id and item.base_unit_id = from_unit_id)
        )
      union all
      select 1
      from public.purchase_order_lines line
      join public.inventory_items item
        on item.organization_id = line.organization_id
       and item.id = line.inventory_item_id
      join public.purchase_orders purchase_order
        on purchase_order.organization_id = line.organization_id
       and purchase_order.id = line.purchase_order_id
      where line.organization_id = p_organization_id
        and purchase_order.status in ('draft', 'submitted', 'partially_received')
        and (item_id is null or item.id = item_id)
        and (
          (line.unit_id = from_unit_id and item.base_unit_id = to_unit_id)
          or (line.unit_id = to_unit_id and item.base_unit_id = from_unit_id)
        )
    ) then
      raise exception 'Deactivate dependent purchase packs, recipes, and open orders first'
        using errcode = '23514';
    end if;
    select * into existing_conversion from public.unit_conversions conversion
    where conversion.id = target_id for update;
    if existing_conversion.id is not null
      and existing_conversion.organization_id <> p_organization_id then
      raise exception 'Unit conversion not found' using errcode = 'P0002';
    end if;
    if existing_conversion.id is null then
      insert into public.unit_conversions (
        id, organization_id, from_unit_id, to_unit_id,
        multiplier, item_id, is_active
      ) values (
        target_id, p_organization_id, from_unit_id, to_unit_id,
        multiplier_value, item_id, active_value
      );
    else
      update public.unit_conversions conversion
      set from_unit_id = from_unit_id,
          to_unit_id = to_unit_id,
          multiplier = multiplier_value,
          item_id = item_id,
          is_active = active_value
      where conversion.id = target_id;
    end if;

  elsif clean_command = 'category.save' then
    clean_name := nullif(btrim(p_payload ->> 'name'), '');
    parent_id := nullif(p_payload ->> 'parentId', '')::uuid;
    active_value := coalesce((p_payload ->> 'isActive')::boolean, true);
    if clean_name is null or length(clean_name) > 120 or parent_id = target_id then
      raise exception 'A valid category name and parent are required' using errcode = '22023';
    end if;
    if parent_id is not null and not exists (
      select 1 from public.inventory_categories category
      where category.id = parent_id and category.organization_id = p_organization_id and category.is_active
    ) then
      raise exception 'Parent category must be active in this organization' using errcode = '23514';
    end if;
    if parent_id is not null and exists (
      with recursive ancestors as (
        select category.id, category.parent_id
        from public.inventory_categories category where category.id = parent_id
        union all
        select category.id, category.parent_id
        from public.inventory_categories category
        join ancestors on category.id = ancestors.parent_id
      )
      select 1 from ancestors where id = target_id
    ) then
      raise exception 'Category hierarchy cannot contain a cycle' using errcode = '23514';
    end if;
    select * into existing_category from public.inventory_categories category
    where category.id = target_id for update;
    if existing_category.id is not null and existing_category.organization_id <> p_organization_id then
      raise exception 'Inventory category not found' using errcode = 'P0002';
    end if;
    if not active_value and exists (
      select 1 from public.inventory_categories category
      where category.parent_id = target_id and category.is_active
      union all
      select 1 from public.inventory_items item
      where item.category_id = target_id and item.is_active
    ) then
      raise exception 'Deactivate or move dependent items and categories first'
        using errcode = '23514';
    end if;
    if existing_category.id is null then
      insert into public.inventory_categories (
        id, organization_id, name, parent_id, is_active
      ) values (target_id, p_organization_id, clean_name, parent_id, active_value);
    else
      update public.inventory_categories category
      set name = clean_name, parent_id = parent_id,
          is_active = active_value
      where category.id = target_id;
    end if;

  elsif clean_command = 'vendor.save' then
    clean_name := nullif(btrim(p_payload ->> 'name'), '');
    clean_account := nullif(btrim(p_payload ->> 'accountNumber'), '');
    clean_contact := nullif(btrim(p_payload ->> 'contactName'), '');
    clean_email := nullif(lower(btrim(p_payload ->> 'email')), '');
    clean_phone := nullif(btrim(p_payload ->> 'phone'), '');
    clean_terms := nullif(btrim(p_payload ->> 'paymentTerms'), '');
    active_value := coalesce((p_payload ->> 'isActive')::boolean, true);
    if clean_name is null or length(clean_name) > 160
      or length(coalesce(clean_account, '')) > 120
      or length(coalesce(clean_contact, '')) > 160
      or length(coalesce(clean_email, '')) > 320
      or length(coalesce(clean_phone, '')) > 80
      or length(coalesce(clean_terms, '')) > 160
      or (clean_email is not null and clean_email !~ '^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]+$') then
      raise exception 'Valid vendor details are required' using errcode = '22023';
    end if;
    select * into existing_vendor from public.vendors vendor
    where vendor.id = target_id for update;
    if existing_vendor.id is not null and existing_vendor.organization_id <> p_organization_id then
      raise exception 'Vendor not found' using errcode = 'P0002';
    end if;
    if not active_value and exists (
      select 1 from public.purchase_orders purchase_order
      where purchase_order.organization_id = p_organization_id
        and purchase_order.vendor_id = target_id
        and purchase_order.status in ('draft', 'submitted', 'partially_received')
    ) then
      raise exception 'Open purchase orders must be completed or cancelled first'
        using errcode = '23514';
    end if;
    if existing_vendor.id is null then
      insert into public.vendors (
        id, organization_id, name, account_number, contact_name,
        email, phone, payment_terms, is_active
      ) values (
        target_id, p_organization_id, clean_name, clean_account, clean_contact,
        clean_email, clean_phone, clean_terms, active_value
      );
    else
      update public.vendors vendor
      set name = clean_name,
          account_number = clean_account,
          contact_name = clean_contact,
          email = clean_email,
          phone = clean_phone,
          payment_terms = clean_terms,
          is_active = active_value
      where vendor.id = target_id;
      if not active_value then
        update public.vendor_items vendor_item
        set is_active = false
        where vendor_item.organization_id = p_organization_id
          and vendor_item.vendor_id = target_id and vendor_item.is_active;
      end if;
    end if;

  elsif clean_command = 'item.save' then
    clean_name := nullif(btrim(p_payload ->> 'name'), '');
    clean_sku := nullif(btrim(p_payload ->> 'sku'), '');
    clean_description := nullif(btrim(p_payload ->> 'description'), '');
    category_id := nullif(p_payload ->> 'categoryId', '')::uuid;
    base_unit_id := (p_payload ->> 'baseUnitId')::uuid;
    track_value := coalesce((p_payload ->> 'trackInventory')::boolean, true);
    active_value := coalesce((p_payload ->> 'isActive')::boolean, true);
    if base_unit_id is null or clean_name is null or length(clean_name) > 160
      or length(coalesce(clean_sku, '')) > 120
      or length(coalesce(clean_description, '')) > 4000 then
      raise exception 'Valid inventory item details are required' using errcode = '22023';
    end if;
    if not exists (
      select 1 from public.measurement_units unit
      where unit.id = base_unit_id and unit.organization_id = p_organization_id and unit.is_active
    ) then
      raise exception 'The canonical base unit must be active in this organization'
        using errcode = '23514';
    end if;
    if category_id is not null and not exists (
      select 1 from public.inventory_categories category
      where category.id = category_id and category.organization_id = p_organization_id and category.is_active
    ) then
      raise exception 'The selected category must be active in this organization'
        using errcode = '23514';
    end if;
    select * into existing_item from public.inventory_items item
    where item.id = target_id for update;
    if existing_item.id is not null and existing_item.organization_id <> p_organization_id then
      raise exception 'Inventory item not found' using errcode = 'P0002';
    end if;
    if existing_item.id is not null and existing_item.base_unit_id <> base_unit_id
      and exists (
        select 1 from public.inventory_transactions transaction
        where transaction.organization_id = p_organization_id
          and transaction.inventory_item_id = target_id
      ) then
      raise exception 'An item with ledger evidence cannot change canonical base unit'
        using errcode = '23514';
    end if;
    if not track_value and coalesce((
      select sum(transaction.quantity_delta)
      from public.inventory_transactions transaction
      where transaction.organization_id = p_organization_id
        and transaction.inventory_item_id = target_id
    ), 0) <> 0 then
      raise exception 'Tracked inventory with on-hand stock cannot be disabled'
        using errcode = '23514';
    end if;
    if not active_value and exists (
      select 1
      from public.purchase_order_lines line
      join public.purchase_orders purchase_order on purchase_order.id = line.purchase_order_id
      where line.organization_id = p_organization_id
        and line.inventory_item_id = target_id
        and purchase_order.status in ('draft', 'submitted', 'partially_received')
      union all
      select 1
      from public.recipe_ingredients ingredient
      join public.recipes recipe on recipe.id = ingredient.recipe_id
      where ingredient.organization_id = p_organization_id
        and ingredient.inventory_item_id = target_id and recipe.is_active
    ) then
      raise exception 'Open orders and active recipes must be resolved before item deactivation'
        using errcode = '23514';
    end if;
    if existing_item.id is null then
      insert into public.inventory_items (
        id, organization_id, category_id, base_unit_id, name,
        sku, description, track_inventory, is_active
      ) values (
        target_id, p_organization_id, category_id, base_unit_id, clean_name,
        clean_sku, clean_description, track_value, active_value
      );
    else
      update public.inventory_items item
      set category_id = category_id,
          base_unit_id = base_unit_id,
          name = clean_name,
          sku = clean_sku,
          description = clean_description,
          track_inventory = track_value,
          is_active = active_value
      where item.id = target_id;
      if not active_value then
        update public.vendor_items vendor_item
        set is_active = false
        where vendor_item.organization_id = p_organization_id
          and vendor_item.inventory_item_id = target_id and vendor_item.is_active;
        update public.unit_conversions conversion
        set is_active = false
        where conversion.organization_id = p_organization_id
          and conversion.item_id = target_id and conversion.is_active;
      end if;
    end if;

  elsif clean_command = 'vendor_item.save' then
    vendor_id := (p_payload ->> 'vendorId')::uuid;
    item_id := (p_payload ->> 'inventoryItemId')::uuid;
    unit_id := (p_payload ->> 'purchaseUnitId')::uuid;
    quantity_value := (p_payload ->> 'packQuantity')::numeric;
    clean_sku := nullif(btrim(p_payload ->> 'vendorSku'), '');
    price_cents := nullif(p_payload ->> 'lastPriceCents', '')::bigint;
    effective_at := coalesce(nullif(p_payload ->> 'priceEffectiveAt', '')::timestamptz, clock_timestamp());
    preferred_value := coalesce((p_payload ->> 'isPreferred')::boolean, false);
    active_value := coalesce((p_payload ->> 'isActive')::boolean, true);
    if vendor_id is null or item_id is null or unit_id is null
      or quantity_value is null or effective_at is null
      or quantity_value <= 0 or quantity_value >= 1000000000000
      or scale(quantity_value) > 4
      or length(coalesce(clean_sku, '')) > 120
      or (price_cents is not null and (price_cents < 0 or price_cents > 9000000000000000))
      or effective_at > clock_timestamp() + interval '366 days' then
      raise exception 'Valid vendor purchase details are required' using errcode = '22023';
    end if;
    select * into existing_vendor from public.vendors vendor
    where vendor.id = vendor_id and vendor.organization_id = p_organization_id and vendor.is_active;
    select * into existing_item from public.inventory_items item
    where item.id = item_id and item.organization_id = p_organization_id and item.is_active;
    if existing_vendor.id is null or existing_item.id is null
      or not exists (
        select 1 from public.measurement_units unit
        where unit.id = unit_id and unit.organization_id = p_organization_id and unit.is_active
      ) then
      raise exception 'Vendor, item, and purchase unit must be active tenant records'
        using errcode = '23514';
    end if;
    perform private.inventory_conversion_multiplier(
      p_organization_id, item_id, unit_id, existing_item.base_unit_id
    );
    select * into existing_vendor_item from public.vendor_items vendor_item
    where vendor_item.id = target_id for update;
    if existing_vendor_item.id is not null
      and existing_vendor_item.organization_id <> p_organization_id then
      raise exception 'Vendor purchase item not found' using errcode = 'P0002';
    end if;
    if preferred_value then
      update public.vendor_items vendor_item
      set is_preferred = false
      where vendor_item.organization_id = p_organization_id
        and vendor_item.inventory_item_id = item_id
        and vendor_item.id <> target_id and vendor_item.is_preferred;
    end if;
    if existing_vendor_item.id is null then
      insert into public.vendor_items (
        id, organization_id, vendor_id, inventory_item_id, purchase_unit_id,
        vendor_sku, pack_quantity, last_price_cents, is_preferred, is_active
      ) values (
        target_id, p_organization_id, vendor_id, item_id, unit_id,
        clean_sku, quantity_value, price_cents, preferred_value, active_value
      );
    else
      update public.vendor_items vendor_item
      set vendor_id = vendor_id,
          inventory_item_id = item_id,
          purchase_unit_id = unit_id,
          vendor_sku = clean_sku,
          pack_quantity = quantity_value,
          last_price_cents = price_cents,
          is_preferred = preferred_value,
          is_active = active_value
      where vendor_item.id = target_id;
    end if;
    if price_cents is not null and active_value then
      insert into public.item_price_history (
        organization_id, inventory_item_id, vendor_id, unit_id,
        unit_price_cents, effective_at, source_type, source_id
      ) values (
        p_organization_id, item_id, vendor_id, unit_id,
        price_cents, effective_at, 'catalog_configuration', target_id
      );
    end if;

  elsif clean_command = 'par.set' then
    quantity_value := (p_payload ->> 'parQuantity')::numeric;
    reorder_value := nullif(p_payload ->> 'reorderQuantity', '')::numeric;
    if quantity_value is null or effective_date < date '1900-01-01'
      or effective_date > current_date + 3650
      or quantity_value < 0 or quantity_value >= 1000000000000
      or scale(quantity_value) > 4
      or (reorder_value is not null and (
        reorder_value < 0 or reorder_value > quantity_value or scale(reorder_value) > 4
      )) then
      raise exception 'Par and reorder quantities are invalid' using errcode = '22023';
    end if;
    if not exists (
      select 1 from public.locations location
      where location.id = location_id and location.organization_id = p_organization_id and location.is_active
    ) or not exists (
      select 1 from public.inventory_items item
      where item.id = item_id and item.organization_id = p_organization_id and item.is_active
    ) then
      raise exception 'Par levels require an active tenant location and item'
        using errcode = '23514';
    end if;
    if existing_par_id is null then
      insert into public.inventory_par_levels (
        id, organization_id, location_id, inventory_item_id,
        par_quantity, reorder_quantity, effective_from
      ) values (
        target_id, p_organization_id, location_id, item_id,
        quantity_value, reorder_value, effective_date
      );
    else
      update public.inventory_par_levels par
      set par_quantity = quantity_value,
          reorder_quantity = reorder_value
      where par.id = existing_par_id;
    end if;

  elsif clean_command = 'recipe.save' then
    recipe_id := target_id;
    clean_name := nullif(btrim(p_payload ->> 'name'), '');
    quantity_value := (p_payload ->> 'yieldQuantity')::numeric;
    unit_id := (p_payload ->> 'yieldUnitId')::uuid;
    price_cents := nullif(p_payload ->> 'menuPriceCents', '')::bigint;
    active_value := coalesce((p_payload ->> 'isActive')::boolean, true);
    ingredients := coalesce(p_payload -> 'ingredients', '[]'::jsonb);
    if unit_id is null or clean_name is null or length(clean_name) > 160
      or quantity_value is null or quantity_value <= 0 or quantity_value >= 1000000000000
      or scale(quantity_value) > 4
      or (price_cents is not null and (price_cents < 0 or price_cents > 9000000000000000))
      or jsonb_typeof(ingredients) <> 'array'
      or jsonb_array_length(ingredients) > 500
      or (active_value and jsonb_array_length(ingredients) = 0) then
      raise exception 'Valid recipe yield, price, and ingredients are required'
        using errcode = '22023';
    end if;
    if not exists (
      select 1 from public.measurement_units unit
      where unit.id = unit_id and unit.organization_id = p_organization_id and unit.is_active
    ) then
      raise exception 'Recipe yield unit must be active in this organization'
        using errcode = '23514';
    end if;
    if exists (
      select 1 from jsonb_array_elements(ingredients) ingredient
      where jsonb_typeof(ingredient) <> 'object'
        or not (ingredient ?& array['inventoryItemId', 'unitId', 'quantity', 'wasteFactor'])
        or (ingredient ->> 'quantity')::numeric <= 0
        or (ingredient ->> 'quantity')::numeric >= 1000000000000
        or scale((ingredient ->> 'quantity')::numeric) > 6
        or (ingredient ->> 'wasteFactor')::numeric < 0
        or (ingredient ->> 'wasteFactor')::numeric >= 1
        or scale((ingredient ->> 'wasteFactor')::numeric) > 6
    ) or (
      select count(*) <> count(distinct ingredient ->> 'inventoryItemId')
      from jsonb_array_elements(ingredients) ingredient
    ) then
      raise exception 'Recipe ingredients are invalid or duplicated' using errcode = '22023';
    end if;
    if (
      select count(*)
      from jsonb_array_elements(ingredients) ingredient
      join public.inventory_items item
        on item.id = (ingredient ->> 'inventoryItemId')::uuid
       and item.organization_id = p_organization_id and item.is_active
      join public.measurement_units unit
        on unit.id = (ingredient ->> 'unitId')::uuid
       and unit.organization_id = p_organization_id and unit.is_active
      where private.inventory_conversion_multiplier(
        p_organization_id, item.id, unit.id, item.base_unit_id
      ) > 0
    ) <> jsonb_array_length(ingredients) then
      raise exception 'Every ingredient requires an active item and canonical unit'
        using errcode = '23514';
    end if;
    perform pg_advisory_xact_lock(hashtextextended('inventory-recipe:' || recipe_id::text, 0));
    select * into existing_recipe from public.recipes recipe
    where recipe.id = recipe_id for update;
    if existing_recipe.id is not null and existing_recipe.organization_id <> p_organization_id then
      raise exception 'Recipe not found' using errcode = 'P0002';
    end if;
    if existing_recipe.id is null then
      insert into public.recipes (
        id, organization_id, name, yield_quantity,
        yield_unit_id, menu_price_cents, is_active
      ) values (
        recipe_id, p_organization_id, clean_name, quantity_value,
        unit_id, price_cents, active_value
      );
    else
      update public.recipes recipe
      set name = clean_name,
          yield_quantity = quantity_value,
          yield_unit_id = unit_id,
          menu_price_cents = price_cents,
          is_active = active_value
      where recipe.id = recipe_id;
      delete from public.recipe_ingredients ingredient
      where ingredient.recipe_id = recipe_id;
    end if;
    insert into public.recipe_ingredients (
      organization_id, recipe_id, inventory_item_id,
      unit_id, quantity, waste_factor
    )
    select p_organization_id, recipe_id,
      (ingredient ->> 'inventoryItemId')::uuid,
      (ingredient ->> 'unitId')::uuid,
      (ingredient ->> 'quantity')::numeric(16,6),
      (ingredient ->> 'wasteFactor')::numeric(7,6)
    from jsonb_array_elements(ingredients) ingredient;

    select coalesce(jsonb_agg(jsonb_build_object(
      'inventoryItemId', ingredient.inventory_item_id,
      'unitId', ingredient.unit_id,
      'quantity', ingredient.quantity,
      'wasteFactor', ingredient.waste_factor
    ) order by ingredient.inventory_item_id), '[]'::jsonb)
    into snapshot_ingredients
    from public.recipe_ingredients ingredient
    where ingredient.recipe_id = recipe_id;
    select coalesce(max(version.version_number), 0) + 1
    into version_number
    from public.inventory_recipe_versions version
    where version.recipe_id = recipe_id;
    insert into public.inventory_recipe_versions (
      organization_id, recipe_id, version_number, snapshot, changed_by
    ) values (
      p_organization_id, recipe_id, version_number,
      jsonb_build_object(
        'name', clean_name,
        'yieldQuantity', quantity_value,
        'yieldUnitId', unit_id,
        'menuPriceCents', price_cents,
        'isActive', active_value,
        'ingredients', snapshot_ingredients
      ),
      actor_id
    );
  end if;

  perform private.complete_operation_request(p_request_id);
  return jsonb_build_object(
    'id', target_id,
    'command', clean_command,
    'replayed', false
  );
exception
  when invalid_text_representation or numeric_value_out_of_range or datetime_field_overflow then
    raise exception 'Invalid inventory catalog command value' using errcode = '22023';
end
$$;

revoke insert, update, delete on public.measurement_units from authenticated;
revoke insert, update, delete on public.unit_conversions from authenticated;
revoke insert, update, delete on public.inventory_categories from authenticated;
revoke insert, update, delete on public.vendors from authenticated;
revoke insert, update, delete on public.inventory_items from authenticated;
revoke insert, update, delete on public.vendor_items from authenticated;
revoke insert, update, delete on public.item_price_history from authenticated;
revoke insert, update, delete on public.inventory_par_levels from authenticated;
revoke insert, update, delete on public.recipes from authenticated;
revoke insert, update, delete on public.recipe_ingredients from authenticated;
revoke all on public.inventory_recipe_versions from public, anon, authenticated;
grant select on public.inventory_recipe_versions to authenticated;

revoke all on function public.configure_inventory_catalog(uuid, uuid, text, jsonb)
from public, anon, authenticated;
grant execute on function public.configure_inventory_catalog(uuid, uuid, text, jsonb)
to authenticated;

comment on function public.configure_inventory_catalog(uuid, uuid, text, jsonb)
is 'Owner/Admin-only, actor-derived, idempotent inventory catalog configuration without destructive deletes.';
