import {expect,it,vi} from "vitest";
vi.mock("@/lib/communications.server",()=>({logCommunicationEvent:vi.fn()}));
vi.mock("@/lib/twilio.server",()=>({readTwilioForm:async(r:Request)=>({params:new URLSearchParams(await r.text())}),validateTwilioRequest:()=>true,twilioSmsEnabled:()=>false,twilioRestClient:()=>({calls:()=>({fetch:async()=>({to:"+12025550101"})})}),twilioForwardNumbers:()=>({donald:"+12025550101",maris:"+12025550102"}),twilioPhoneNumber:()=>"+13328779035",twilioAbsoluteUrl:(p:string)=>`https://operations.leyardny.com${p}`,xmlResponse:(x:string)=>new Response(x)}));
import {POST} from "@/app/api/twilio/voice/result/route";
function request(bridged:string,status:string){return new Request('https://operations.leyardny.com/api/twilio/voice/result',{method:'POST',body:new URLSearchParams({DialBridged:bridged,DialCallStatus:status})});}
it('offers voicemail if a completed dial leg did not bridge a human',async()=>{expect(await (await POST(request('false','completed'))).text()).toContain('<Record');});
it('does not offer voicemail after a successfully bridged call',async()=>{const text=await (await POST(request('true','completed'))).text();expect(text).not.toContain('<Record');expect(text).toContain('<Hangup');});

it('retries the other phone after a screened-out completed leg',async()=>{const r=new Request('https://operations.leyardny.com/api/twilio/voice/result',{method:'POST',body:new URLSearchParams({DialBridged:'false',DialCallStatus:'completed',DialCallSid:'CA'+'1'.repeat(32)})});const text=await(await POST(r)).text();expect(text).toContain('+12025550102');expect(text).toContain('retried=1');expect(text).not.toContain('<Record');});
it('does not loop after the other phone also fails screening',async()=>{const r=new Request('https://operations.leyardny.com/api/twilio/voice/result?retried=1',{method:'POST',body:new URLSearchParams({DialBridged:'false',DialCallStatus:'completed',DialCallSid:'CA'+'1'.repeat(32)})});const text=await(await POST(r)).text();expect(text).toContain('<Record');expect(text).not.toContain('<Dial');});
