import {beforeEach,expect,it,vi} from "vitest";
const mocks=vi.hoisted(()=>({access:vi.fn(),download:vi.fn(),upload:vi.fn(),send:vi.fn(),call:vi.fn(),consent:vi.fn(),recordConsent:vi.fn(),from:vi.fn()}));
vi.mock("@/lib/phone-access.server",()=>({requirePhoneAccess:mocks.access}));
vi.mock("@/lib/communications.server",()=>({hasServiceSmsConsent:mocks.consent,recordServiceSmsConsent:mocks.recordConsent}));
vi.mock("@/lib/supabase/admin",()=>({createAdminClient:()=>({from:mocks.from,storage:{from:()=>({download:mocks.download,upload:mocks.upload})}})}));
vi.mock("@/lib/twilio.server",()=>({twilioAbsoluteUrl:(p:string)=>`https://operations.leyardny.com${p}`,twilioPhoneNumber:()=>"+13328779035",twilioForwardNumbers:()=>({donald:"+12025550101",maris:"+12025550102"}),normalizeE164:(n:string)=>{if(!/^\+[1-9]\d{7,14}$/.test(n))throw Error();return n;},twilioSmsEnabled:()=>true,sendTwilioMessage:mocks.send,createTwilioCall:mocks.call}));
import {POST} from "@/app/api/phone/route";
const origin="https://operations.leyardny.com";
function request(extra:Record<string,unknown>={},source=origin){return new Request(`${origin}/api/phone`,{method:"POST",headers:{origin:source,"content-type":"application/json"},body:JSON.stringify({action:"sms",requestId:"12345678-1234-4234-8234-123456789abc",to:"+12025550199",body:"Guest-care reply",...extra})});}
beforeEach(()=>{vi.stubEnv("NEXT_PUBLIC_APP_URL",origin);vi.clearAllMocks();mocks.access.mockResolvedValue({organization:{id:"org"},identity:{userId:"owner"}});mocks.download.mockResolvedValue({data:null,error:{message:"Object not found"}});mocks.upload.mockResolvedValue({error:null});mocks.consent.mockResolvedValue(true);mocks.send.mockResolvedValue({sid:"SMtest",status:"queued"});mocks.from.mockImplementation(()=>{const q={select:vi.fn().mockReturnThis(),eq:vi.fn().mockReturnThis(),contains:vi.fn().mockReturnThis(),gte:vi.fn().mockResolvedValue({count:0,error:null}),insert:vi.fn().mockResolvedValue({error:null})};return q;});});
it("rejects cross-origin writes before account access",async()=>{expect((await POST(request({},"https://other.example"))).status).toBe(403);expect(mocks.send).not.toHaveBeenCalled();});
it("never calls the carrier when account access fails",async()=>{mocks.access.mockRejectedValue(new Response("Forbidden",{status:403}));expect((await POST(request())).status).toBe(403);expect(mocks.send).not.toHaveBeenCalled();});
it("requires guest-care permission for a new recipient",async()=>{mocks.consent.mockResolvedValue(false);expect((await POST(request())).status).toBe(400);expect(mocks.upload).not.toHaveBeenCalled();expect(mocks.send).not.toHaveBeenCalled();});
it("atomically claims a request before sending and reports queued honestly",async()=>{const r=await POST(request());expect(r.status).toBe(201);expect(await r.json()).toEqual({sid:"SMtest",status:"queued"});expect(mocks.upload.mock.calls[0][2].upsert).toBe(false);expect(mocks.upload.mock.invocationCallOrder[0]).toBeLessThan(mocks.send.mock.invocationCallOrder[0]);});
it("a competing claim cannot send a duplicate text",async()=>{mocks.upload.mockResolvedValueOnce({error:{message:"already exists"}});expect((await POST(request())).status).toBe(409);expect(mocks.send).not.toHaveBeenCalled();});
it("keeps an ambiguous carrier request claimed",async()=>{mocks.send.mockRejectedValue(Error("timeout"));expect((await POST(request())).status).toBe(503);expect(mocks.upload).toHaveBeenCalledTimes(1);expect(mocks.send).toHaveBeenCalledOnce();});
it("does not turn accepted delivery into failure if result persistence fails",async()=>{mocks.upload.mockResolvedValueOnce({error:null}).mockResolvedValueOnce({error:{message:"unavailable"}});expect((await POST(request())).status).toBe(201);expect(mocks.send).toHaveBeenCalledOnce();});
it("refuses reuse of another operator's claim",async()=>{mocks.download.mockResolvedValue({data:new Blob([JSON.stringify({fingerprint:"other",userId:"another-owner",status:"queued"})]),error:null});expect((await POST(request())).status).toBe(409);expect(mocks.send).not.toHaveBeenCalled();});

it("allows one owner to call the other through the business number",async()=>{vi.stubEnv("TWILIO_OUTBOUND_ENABLED","true");mocks.call.mockResolvedValue({sid:"CAtest",status:"queued"});const r=await POST(request({action:"call",staff:"donald",to:"+12025550102"}));expect(r.status).toBe(201);expect(mocks.call).toHaveBeenCalledWith(expect.objectContaining({to:"+12025550101"}));});
it("blocks a callback to the same cellphone as the destination",async()=>{vi.stubEnv("TWILIO_OUTBOUND_ENABLED","true");expect((await POST(request({action:"call",staff:"donald",to:"+12025550101"}))).status).toBe(400);expect(mocks.call).not.toHaveBeenCalled();});
